services:
  - type: web
    name: pockly-server
    env: node
    rootDir: pockly-server
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
